CREATE SCHEMA IF NOT EXISTS BNKY;
SET SCHEMA BNKY;
CREATE TABLE IF NOT EXISTS BNKY.POKE01_RQST (TX_IP VARCHAR(18), FH_CREATION DATE DEFAULT SYSDATE NOT NULL, TX_METHOD VARCHAR(15), NU_TIME_REQUEST NUMBER(3), TX_REQUEST VARCHAR(30), TX_RESPONSE VARCHAR(1000));

SET SCHEMA PUBLIC;
